### ISSUE TITLE
Error during failsafe response: Pundit::AuthorizationNotPerformedError

### ISSUE THREAD

**Issue by atstockland** [mirego/gaffe#20]
I can't get past this Pundit error.  Have you used Pundit with gaffe?  The 'AuthorizationNotPerformedError' seems to be a general Pundit error.  I have all error views, I have a policy method for each view.  Not sure where or why this is preventing gaffe from returning the error page.

Here is the trace:

Processing by Gaffe::ErrorsController#show as HTML
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
  School Load (0.9ms)  SELECT  "schools".* FROM "schools" WHERE "schools"."id" = $1 LIMIT 1  [["id", 1]]
  Rendered errors/internal_server_error.html.erb within layouts/error (0.2ms)
Completed 406 Not Acceptable in 41ms
Error during failsafe response: Pundit::AuthorizationNotPerformedError
  /Users/XXXX/.rvm/gems/ruby-2.2.0-rc1@XXXX/gems/pundit-0.3.0/lib/pundit.rb:58:in `verify_authorized'

**Comment by remiprev** [comment]
The `Error during failsafe response` message indicates that an error occurred while Gaffe was trying to render its view and therefore Rails is rendering its failsafe response.

**Comment by remiprev** [comment]
The `Pundit::AuthorizationNotPerformedError` error is raised when Gaffe is trying to render its page. To prevent this, you’ll have to avoid raising the error. Maybe skip a `before_action` filter in your `ErrorsController`?

**Comment by remiprev** [comment]
I’m going to close down this issue since there has been no response from OP.

**Comment by atstockland** [comment]
Thanks!  Sorry for the late response.  I was unable to resolve this and simply stopped using Gaffe.
