### ISSUE TITLE
Fallback static pages are not rendered

### ISSUE THREAD

**Issue by brandoncc** [mirego/gaffe#25]
When my error page encounters an exception during render, the fallback static `public/500.html` is not rendered. Instead I see the Rails default text:

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

I fixed that using a rescue block:

```ruby
  def show
    render "errors/#{@rescue_response}", status: @status_code, layout: (logged_in? ? 'application' : 'external')
  rescue
    # For some reason the static 500.html is not being rendered as a fallback,
    # this fixes it. When the render above encounters an exception, this will
    # catch it and render the static page.
    render file: 'public/500.html', status: 500, layout: false
  end
```

I then figured out that this also affects other error pages, so I used this code which fixed it:

```ruby
  def show
    render "errors/#{@rescue_response}", status: @status_code, layout: (logged_in? ? 'application' : 'external')
  rescue
    # For some reason the static fallback pages are not being rendered.
    # This rescue block fixes it. When the render above encounters an exception, this will
    # catch it and render the static page.
    if File.exists?("#{Rails.root.join('public', "#{@status_code}.html")}")
      render file: "public/#{@status_code}.html", status: @status_code, layout: false
    else
      render file: 'public/500.html', status: 500, layout: false
    end
  end
```

Am I doing something wrong which is causing gaffe to not handle this fallback gracefully automatically?

**Comment by remiprev** [comment]
Unfortunately, Gaffe sets the `exceptions_app` option to a custom Rack app and let it handle exceptions. This overrides the [default exception catching mechanism in Rails](https://github.com/rails/rails/blob/0ebb0f61c3c66df517c1277265f337a09928da86/railties/lib/rails/application/default_middleware_stack.rb#L113).

If you want to implement some kind of static file fallback, you have to implement it yourself, just like you did in your last example :smile: 

I’m going to close this issue, feel free to re-open it if you have other questions.
