### ISSUE TITLE
Don't work config.errors_controller in Test

### ISSUE THREAD

**Issue by kbaba1001** [mirego/gaffe#26]
@mirego Thinks very nice gem, I liked gaffe.

I set `config/initializers/gaffe.rb`:

```ruby
Gaffe.configure do |config|
  config.errors_controller = {
    %r[^/api/] => 'Api::ErrorsController',
    %r[^/] => 'ErrorsController'
  }
end

Gaffe.enable!
```

I wrote request spec (RSpec) in accordance with https://github.com/mirego/gaffe#rails-test-environment .
However, responsed by `Gaffe::ErrorsController`.
I want to be responsed by `Api::ErrorsController` or `ErrorsController`.

I guessed that `@env['REQUEST_URI']` was empty in https://github.com/mirego/gaffe/blob/master/lib/gaffe/errors_controller_resolver.rb#L33 .
Rack::Test is not set environment REQUEST_URI: https://github.com/brynary/rack-test/issues/26

**Comment by remiprev** [comment]
Hi!

Can you paste the test you’re running so we can get a better understanding of what’s going on? Thanks!

**Comment by kbaba1001** [comment]
I investigated.

fail application: https://github.com/kbaba1001/gems_sample/tree/rspec_api_documentation

I'm using [zipmark/rspec_api_documentation](https://github.com/zipmark/rspec_api_documentation).
`rspec_api_documentation` use not `request spec` but `acceptance spec`.
On `acceptance spec`, `@env['REQUEST_URI']` is empty :sweat:

I wrote same spec on `request spec`, then work fine `config.errors_controller` setting.

`gaffe` and `rspec_api_documentation` are incompatible. :disappointed_relieved:
