### ISSUE TITLE
Not working at all in my rails application

### ISSUE THREAD

**Issue by bhanuone** [mirego/gaffe#38]
Rails default error pages are still being displayed instead of custom error pages even after I add this gem. I configured as mentioned in the gem documentation. Not even getting any error to mention here related to this gem but its not working.

**Comment by remiprev** [comment]
@bhanuone Can you please provide more details? Like your Rails version, how you configured it, etc.?

**Comment by bhanuone** [comment]
Thanks for responding @remiprev. Here are some details

> Rails version: 4.2.8
> Ruby version: 2.3.1

```
#config/initializers/gaffe.rb

# Gaffe.configure do |config|
#   config.errors_controller = {
#     %r[/admin] => 'ErrorsController',
#   }
# end

Gaffe.enable!
```

```
# Gemfile

#custom error pages
gem 'gaffe'
```

Here is an error from development server.
![gaffe](https://user-images.githubusercontent.com/3231946/28314269-7887b622-6bd7-11e7-9632-f8be5ea0e045.png)

**Comment by remiprev** [comment]
Did you follow the [development environment instructions](https://github.com/mirego/gaffe#rails-development-environment)?
